; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico32]
platform = espressif32
board = pico32
framework = espidf

monitor_speed = 115200

board_build.cmake_extra_args = 
    -DZ_FEATURE_LINK_SERIAL=1
    -DZ_FEATURE_LINK_TCP=0 
    -DZ_FEATURE_LINK_UDP_UNICAST=0 
    -DZ_TRANSPORT_LEASE=60000 
    -DZ_TRANSPORT_LEASE_EXPIRE_FACTOR=2
;build_unflags = 
;    -DCONFIG_LOG_DEFAULT_LEVEL
build_flags =
    -DZENOH_C_STANDARD=99
    -DZENOH_COMPILER_GCC
    ;-DZ_BATCH_SIZE_TX=1500
    ;-DZ_BATCH_UNICAST_SIZE=2048

    -Wno-missing-field-initializers

    -I include
    -DUSER_TYPE_FILE='"my_ros_types.h"'
    -DZENOH_ESPIDF  ; this was required to build Pico-ROS against Zenoh
    ; -DZENOH_LOG_DEBUG ; helpful to see Zenoh debug log
    ; -DZENOH_LOG_TRACE ; helpful to see where errors are coming from
    ; -DPICOROS_DEBUG
    -I config
lib_deps =
    https://github.com/eclipse-zenoh/zenoh-pico
    https://github.com/eProsima/Micro-CDR

    ;https://github.com/xopxe/picorosso-espidf
    /home/xopxe/workspace_mega/PlatformIO/picorosso-espidf

    ; clone the following repos yourself in the .pio/libdeps/pico32 directory:
    ; https://github.com/Pico-ROS/Pico-ROS-software.git
